[uwsgi]
# 仅使用 Socket 模式（Nginx 代理专用）
socket = 127.0.0.1:8002  ; 改为与 Nginx uwsgi_pass 一致的端口（非8001）
chdir = /home/wangsiyuan/wsy/financial_knowledgegraph_tool/knowledgegraph
wsgi-file = /home/wangsiyuan/wsy/financial_knowledgegraph_tool/knowledgegraph/knowledgegraph/wsgi.py
master = true
processes = 4
vacuum = true
logto = /home/wangsiyuan/wsy/financial_knowledgegraph_tool/knowledgegraph/uwsgi.log
buffer-size = 65535
enable-threads = true  ; 支持多线程
thunder-lock = true    ; 防止多个进程竞争