# Generated by Django 4.2.18 on 2025-02-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledgegraph", "0002_metaknowledge_variable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metaknowledge",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
