# Generated by Django 4.2.18 on 2025-02-16 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("knowledgegraph", "0003_alter_metaknowledge_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metaknowledge",
            name="formula",
        ),
        migrations.RemoveField(
            model_name="variable",
            name="meta_knowledge",
        ),
        migrations.CreateModel(
            name="Formula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("formula_string", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_knowledge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formulas",
                        to="knowledgegraph.metaknowledge",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormulaVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formula_variables",
                        to="knowledgegraph.formula",
                    ),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formula_variables",
                        to="knowledgegraph.variable",
                    ),
                ),
            ],
            options={
                "unique_together": {("formula", "variable")},
            },
        ),
    ]
