# Generated by Django 4.2.18 on 2025-03-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledgegraph", "0004_remove_metaknowledge_formula_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variable",
            name="reference_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
