# Generated by Django 4.2.18 on 2025-03-23 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("knowledgegraph", "0005_variable_reference_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formulavariable",
            options={"verbose_name": "公式变量关联", "verbose_name_plural": "公式变量关联"},
        ),
        migrations.RemoveField(
            model_name="variable",
            name="variable_type",
        ),
        migrations.AddField(
            model_name="variable",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="variable",
            name="variable_meaning",
            field=models.CharField(
                default="", help_text="例如：公司负债率", max_length=255, verbose_name="变量意义"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="formula",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="formula",
            name="formula_string",
            field=models.TextField(verbose_name="公式内容"),
        ),
        migrations.AlterField(
            model_name="formula",
            name="meta_knowledge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formulas",
                to="knowledgegraph.metaknowledge",
                verbose_name="所属元知识",
            ),
        ),
        migrations.AlterField(
            model_name="formula",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="formulavariable",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="formulavariable",
            name="formula",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formula_variables",
                to="knowledgegraph.formula",
                verbose_name="公式",
            ),
        ),
        migrations.AlterField(
            model_name="formulavariable",
            name="variable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formula_variables",
                to="knowledgegraph.variable",
                verbose_name="变量",
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="variable",
            name="reference_count",
            field=models.PositiveIntegerField(default=0, verbose_name="引用计数器"),
        ),
        migrations.AlterField(
            model_name="variable",
            name="variable_name",
            field=models.CharField(max_length=255, verbose_name="变量名称"),
        ),
    ]
